# Generated by Django 4.2 on 2025-11-15 15:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("basic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True, max_length=2048)),
                (
                    "external_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("date_from", models.DateTimeField(blank=True, null=True)),
                ("date_to", models.DateTimeField(blank=True, null=True)),
                ("effective_date_from", models.DateTimeField(blank=True, null=True)),
                ("effective_date_to", models.DateTimeField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("corrected_date_from", models.DateTimeField(blank=True, null=True)),
                ("corrected_date_to", models.DateTimeField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("finish_date", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("interrupted", "Interrupted"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "planned_quantity",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00001"))
                        ],
                    ),
                ),
                (
                    "done_quantity",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="basic.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="basic.product",
                    ),
                ),
                (
                    "production_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="basic.productionline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStateChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_state", models.CharField(max_length=20)),
                ("target_state", models.CharField(max_length=20)),
                ("date_and_time", models.DateTimeField(auto_now_add=True)),
                ("worker", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_changes",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order State Change",
                "verbose_name_plural": "Order State Changes",
                "ordering": ["-date_and_time"],
            },
        ),
    ]
