# Generated by Django 4.2 on 2025-11-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("technologies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="technology",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="technologies.technology",
            ),
        ),
    ]
