# Generated by Django 4.2 on 2025-11-19 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("basic", "0002_workstation_production_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraceabilityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finished_good_batch", models.CharField(max_length=100)),
                ("raw_material_batch", models.CharField(max_length=100)),
                ("quantity_used", models.DecimalField(decimal_places=4, max_digits=15)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "finished_good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traceability_outputs",
                        to="basic.product",
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traceability_inputs",
                        to="basic.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KanbanCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("capacity", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("replenishing", "Replenishing"),
                            ("empty", "Empty"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("last_replenished", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="basic.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_id", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bin", "Bin"),
                            ("tote", "Tote"),
                            ("pallet", "Pallet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("location", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("warehouse", "Warehouse"),
                            ("shop_floor", "Shop Floor"),
                            ("buffer", "Buffer Zone"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="basic.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("material", "location_name", "batch_number")},
            },
        ),
    ]
