# Generated by Django 4.2 on 2025-11-15 17:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production_counting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productioncounting",
            name="done_quantity",
            field=models.DecimalField(
                decimal_places=5,
                default=Decimal("0"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="productioncounting",
            name="rejected_quantity",
            field=models.DecimalField(
                decimal_places=5,
                default=Decimal("0"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
