# Generated by Django 4.2 on 2025-11-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0001_initial"),
        ("production_counting", "0002_alter_productioncounting_done_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productioncounting",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productioncounting",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_counts",
                to="basic.staff",
            ),
        ),
        migrations.AddField(
            model_name="productioncounting",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productioncounting",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "in_progress"), ("completed", "completed")],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
