# Generated by Django 4.2 on 2025-11-19 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("technologies", "0001_initial"),
        ("basic", "0002_workstation_production_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("pass_fail", "Pass/Fail"),
                            ("variable", "Variable Data"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("parameters", models.CharField(blank=True, max_length=255)),
                ("mandatory", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_configs",
                        to="technologies.operation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SPCData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter_name", models.CharField(max_length=100)),
                ("value", models.DecimalField(decimal_places=4, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("machine_id", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="QualityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=100)),
                ("result_value", models.CharField(max_length=100)),
                ("passed", models.BooleanField()),
                ("inspector_name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quality.inspectionconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ncr_number", models.CharField(max_length=100, unique=True)),
                ("issue_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quarantine", "Quarantine"),
                            ("review", "Review"),
                            ("closed", "Closed"),
                        ],
                        default="quarantine",
                        max_length=20,
                    ),
                ),
                ("disposition", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="basic.product"
                    ),
                ),
            ],
        ),
    ]
