# Generated by Django 4.2 on 2025-11-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("technologies", "0001_initial"),
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scheduling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_index", models.PositiveIntegerField(default=0)),
                ("planned_start", models.DateTimeField()),
                ("planned_end", models.DateTimeField()),
                ("duration_seconds", models.PositiveIntegerField()),
                ("buffer_seconds", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("locked", models.BooleanField(default=False)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="technologies.technologyoperationcomponent",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Item",
                "verbose_name_plural": "Schedule Items",
                "ordering": ["order", "sequence_index"],
            },
        ),
    ]
