# Generated by Django 4.2 on 2025-11-15 15:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("basic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True)),
                (
                    "tj",
                    models.IntegerField(
                        default=0, help_text="Time for batch (seconds)"
                    ),
                ),
                (
                    "tpz",
                    models.IntegerField(
                        default=0, help_text="Preparation time (seconds)"
                    ),
                ),
                (
                    "time_next_operation",
                    models.IntegerField(
                        default=0, help_text="Time to next operation (seconds)"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workstations",
                    models.ManyToManyField(
                        blank=True, related_name="operations", to="basic.workstation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation",
                "verbose_name_plural": "Operations",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True, max_length=2048)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("accepted", "Accepted"),
                            ("checked", "Checked"),
                            ("outdated", "Outdated"),
                            ("declined", "Declined"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("master", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="basic.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technology",
                "verbose_name_plural": "Technologies",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="TechnologyOperationComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_number", models.CharField(max_length=255)),
                ("priority", models.IntegerField(default=1)),
                (
                    "tj",
                    models.IntegerField(
                        blank=True, help_text="Override time for batch", null=True
                    ),
                ),
                (
                    "tpz",
                    models.IntegerField(
                        blank=True, help_text="Override preparation time", null=True
                    ),
                ),
                (
                    "time_next_operation",
                    models.IntegerField(
                        blank=True,
                        help_text="Override time to next operation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technology_components",
                        to="technologies.operation",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="technologies.technologyoperationcomponent",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_components",
                        to="technologies.technology",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technology Operation Component",
                "verbose_name_plural": "Technology Operation Components",
                "ordering": ["technology", "node_number"],
            },
        ),
        migrations.CreateModel(
            name="OperationProductOutComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "operation_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_products",
                        to="technologies.technologyoperationcomponent",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_outputs",
                        to="basic.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation Product Out Component",
                "verbose_name_plural": "Operation Product Out Components",
            },
        ),
        migrations.CreateModel(
            name="OperationProductInComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "operation_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_products",
                        to="technologies.technologyoperationcomponent",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_inputs",
                        to="basic.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation Product In Component",
                "verbose_name_plural": "Operation Product In Components",
            },
        ),
    ]
